inventory = {
  { -- inventory 1
    { -- side 1
      "Bone",
      "Wither Skeleton Skull",
      "Coal",
      "Golden Apple",
      "Common Treasure",
      "Cookie",
      "Ender Pearl",
      "Arrow",
      "Uncommon Treasure",
      "Necrotic Bone",
      "Nether Wart",
      "Blaze Rod",
      "Charcoal",
      "Dark Oak Sapling",
      "Dark Oak Wood",
      "Diamond Equipment"
    },
    { -- side 2
      "Cobblestone",
      "Glowstone Dust",
      "Flint",
      "Carrot",
      "Dirt",
      "Redstone",
      "Spider Eye",
      "Potato",
      "Stone",
      "Gunpowder",
      "Gold Coin",
      "Poisonous Potato",
      "Iron Equipment",
      "Vinteum Dust",
      "Enchanted Books",
      "Egg"
    }
  },
  { -- inventory 2
    { -- side 1
      "Zombie Head",
      "Gold Nugget",
      "Lily Pad",
      "String",
      "Chitin Nether",
      "Iron Ingot",
      "Clownfish",
      "Ink Sac",
      "Gold Ingot",
      "Gold Equipment",
      "Pufferfish",
      "Tripwire Hook",
      "Zombie Brain",
      "Raw Fish",
      "Raw Salmon",
      "Name Tag"
    },
    { -- side 2
      "Steel Ingot",
      "Leather",
      "Sugar Canes",
      "Rotten Flesh",
      "Feather",
      "Diamond",
      "Apple",
      "Wheat",
      "Raw Chicken",
      "Saddle",
      "Cactus",
      "Seeds",
      "Clay",
      "Obsidian",
      "Concentrated Essence Berry",
      "Chain Equipment"
    }
  },
  { -- inventory 3
    { -- side 1
      "Sugar Charcoal",
	  "Heart of Undead",
	  "Large Whitestone Bricks",
	  "Copper Ingot",
	  "Pumpkin",
	  "Netherrack",
	  "Aluminum Ingot",
	  "Nothing Yet",
	  "Pumpkin Seeds",
	  "Heart of Darkness",
	  "Creeper Head",
	  "UuMatter Cell",
	  "Glass Bottle",
	  "Nothing Yet",
	  "Tin Ingot",
	  "Nothing Yet",
    },
    { -- side 2
      "Nothing Yet",
    }
  }
}